Updated android_photosync and backup script. IMPORTANT BUGFIX IN CLEANUP
$HOME/.gnupg was added by error to cleanup script

diff --git a/android_photosync b/android_photosync
--- a/android_photosync
+++ b/android_photosync
@@ -24,7 +24,7 @@ readonly SDCARD_BACKUPS=(
 	wegoigo
 )
 readonly APPDATA_BACKUPS=(
-	air.com.rosettastone.mobile.CoursePlayer
+	#air.com.rosettastone.mobile.CoursePlayer
 	com.andrewshu.android.reddit
 	com.android.providers.contacts
 	com.ceco.marshmallow.gravitybox
@@ -32,19 +32,19 @@ readonly APPDATA_BACKUPS=(
 	com.dotgears.swing
 	com.dotgears.flappybird
 	com.duolingo
-	com.estoty.game2048
+	#com.estoty.game2048
 	com.fsck.k9
-	com.handynorth.moneywise_free
+	#com.handynorth.moneywise_free
 	com.lima.doodlejump
 	com.liutoapps.android.memory
 	com.marz.snapprefs
 	com.molodev.galaxir
 	com.quinny898.xposed.googlekeyboardcustomsmileys
-	com.rovio.angrybirds
+	#com.rovio.angrybirds
 	com.rovio.angrybirdsgo
-	com.RunnerGames.game.YooNinja_Lite
+	#com.RunnerGames.game.YooNinja_Lite
 	com.ryansteckler.nlpunbounce
-	com.sega.sonicdash
+	#com.sega.sonicdash
 	com.shazam.android
 	com.snapchat.android
 	com.soa.sega.soniccdlite
@@ -57,7 +57,7 @@ readonly APPDATA_BACKUPS=(
 	de.Maxr1998.xposed.maxlock
 	dev.ukanth.ufirewall
 	net.andchat
-	org.coursera.android
+	#org.coursera.android
 	org.mozilla.firefox
 	org.sufficientlysecure.keychain
 )
@@ -84,7 +84,7 @@ function android_cmd () {
 	local cmd="$@"; shift
 
 	echo "Executing command '${cmd}' via adb" >> "${LOGFILE}"
-	sudo adb shell "${cmd}"
+	sudo adb shell "${cmd}" >> "${LOGFILE}"
 	return_value=$?
 	if [ "${return_value}" != 0 ]; then
 		echo "Return value: ${return_value}" | tee -a "${LOGFILE}" >&2
@@ -97,7 +97,7 @@ function android_cmd_as_root () {
 	local cmd="$@"; shift
 
 	echo "Executing command '${cmd}' as root via adb" >> "${LOGFILE}"
-	sudo adb shell '[ $(whoami) == root ] && '"${cmd} || su -c '${cmd}'"
+	sudo adb shell '[ $(whoami) == root ] && '"${cmd} || su -c '${cmd}'" >> "${LOGFILE}"
 	return_value=$?
 	if [ "${return_value}" != 0 ]; then
 		echo "Return value: ${return_value}" | tee -a "${LOGFILE}" >&2
@@ -142,7 +142,7 @@ function pull_non_local_files () {
 		| grep '>' \
 		| cut -b3- \
 		| while read; do
-			echo -n "Backing up ${REPLY}: "
+			echo -n "Backing up ${REPLY}: " | tee -a "${LOGFILE}" >&2
 			WORKING_FILE="${REPLY}"
 			echo $REPLY
 			local_file=$(echo "${REPLY}" | sed -e "s#${android_directory}#${local_directory}#")
@@ -193,8 +193,7 @@ function backup_app () {
 			rm -r "${APP_BACKUP_DIR}/${directory}.bak"
 		fi
 	else
-		echo "ERROR BACKING UP ${directory}" | tee -a "${LOGFILE}" >&2
-		exit 1
+		echo "ERROR BACKING UP ${directory}; skipping" | tee -a "${LOGFILE}" >&2
 	fi
 	android_cmd "rm -r '/sdcard/${app}' 2>/dev/null"
 	android_cmd "mv '/sdcard/${app}.bak' '/sdcard/${app}' 2>/dev/null"
