Post facebook commit

diff --git a/cleanup b/cleanup
--- a/cleanup
+++ b/cleanup
@@ -1,32 +1,390 @@
 #!/bin/bash
-rm -rf $HOME/.AbiSuite $HOME/.abrt $HOME/.adobe $HOME/.AMD $HOME/.android $HOME/.ansible $HOME/.ansible_async $HOME/.appletviewer $HOME/.aptitude $HOME/.aria2 $HOME/.assaultcube_v1.104 $HOME/.audacity-data $HOME/.cache $HOME/.cgobanrc $HOME/.cinnamon $HOME/.dbus $HOME/.ddd $HOME/.dreamchess $HOME/.dvdcss $HOME/.eclipse $HOME/.elinks $HOME/.emacs.d $HOME/.evolution $HOME/.fontconfig $HOME/.gconfd $HOME/.gdb_history $HOME/.gegl-0.0 $HOME/.getdown $HOME/.gimp-2.8 $HOME/.git-credential-cache $HOME/.gksu.lock $HOME/.gnash $HOME/.gnome $HOME/.gnome2 $HOME/.gnome2_private $HOME/.gnote $HOME/.golly $HOME/.googleearth $HOME/.gstreamer-0.10 $HOME/.gvfs $HOME/.hedgewars $HOME/.icedtea $HOME/.icons $HOME/.isag.cfg $HOME/.java $HOME/.kde $HOME/.lftp $HOME/.links2 $HOME/.macromedia $HOME/.matlab $HOME/.matplotlib $HOME/.mc $HOME/.mcop $HOME/.mission-control $HOME/.mplayer $HOME/.muttator $HOME/.nautilus $HOME/.nedit $HOME/.nv $HOME/.nvimlog $HOME/.octave_hist $HOME/.pdfedit $HOME/.pip $HOME/.pki $HOME/.pulse $HOME/.python_history $HOME/.qt $HOME/.recently-used.xbel $HOME/.redhat $HOME/.scala_history $HOME/.subversion $HOME/.sunstudio $HOME/.swt $HOME/.texmf-var $HOME/.themes $HOME/.thumbnails $HOME/.update-notifier $HOME/.vidalia $HOME/.wireshark
-rm -f $HOME/.aspell* $HOME/.cuda-gdbinit $HOME/.esd_auth $HOME/.gnuplot_history $HOME/.gtk-bookmarks $HOME/.history $HOME/.ICEauthority $HOME/.imsettings.log $HOME/.lesshst $HOME/.ophcrackrc $HOME/.pulse-cookie $HOME/.recently-used $HOME/.scala_history $HOME/.sudo_as_admin_successful $HOME/.tilp $HOME/.viminfo $HOME/.vim/.netrwhist $HOME/.wget-hsts $HOME/.xfce4-session.verbose-log* $HOME/.xsession $HOME/.xsession-errors* $HOME/.ypp_42
-#rm -rf $HOME/.cache/aptitude $HOME/.cache/banshee-1 $HOME/.cache/chromium $HOME/.cache/dconf $HOME/.cache/docky $HOME/.cache/fontconfig $HOME/.cache/gegl-0.2 $HOME/.cache/gstreamer-1.0 $HOME/.cache/gnome-screenshot $HOME/.cache/gnome-system-monitor.* $HOME/.cache/gvfs-burn $HOME/.cache/mozilla $HOME/.cache/pip $HOME/.cache/quodlibet $HOME/.cache/software-center $HOME/.cache/spotify/Data $HOME/.cache/thumbnails
-#rm -f $HOME/.cache/motd.legal-displayed $HOME/.cache/event-sound-cache.tdb*
-cd $HOME/.mozilla 2>/dev/null
-rmdir extensions 2>/dev/null
-cd firefox 2>/dev/null
-rm -f $HOME/.AndroidStudio2.0/config/options/usage.statistics.xml $HOME/.AndroidStudio2.0/config/options/feature.usage.statistics.xml $HOME/.AndroidStudio2.0/config/options/statistics.application.usages.xml
-for profile in $(ls -d *.default 2>/dev/null)
-do
-	cd $profile
-	rm -rf startupCache Cache bookmarkbackups thumbnails OfflineCache thumbnails
-	rm -f adblockplus/patterns-backup* adblockplus/cache.js chromeappstore.sqlite
-	cd ..
-done
-rm -f /tmp/gnash-cookies.* $(locate recently-used.xbel)
-rm -rf $HOME/.config/abrt $HOME/.config/chromium/Default/Local\ Storage $HOME/.config/cinnamon-session $HOME/.config/clipit $HOME/.config/DjVuLibre $HOME/.config/enchant $HOME/.config/evince $HOME/.config/evolution $HOME/.config/gnome-disk-utility $HOME/.config/gnome-initial-setup-done $HOME/.config/gnome-session $HOME/.config/goa-1.0 $HOME/.config/google-chrome/Default/Local\ Storage $HOME/.config/google-googletalkplugin $HOME/.config/gtk-2.0 $HOME/.config/guvcview2 $HOME/.config/htop $HOME/.config/ibus $HOME/.config/imsettings $HOME/.config/kazam $HOME/.config/libreoffice $HOME/.config/libvirt $HOME/.config/menus $HOME/.nemo $HOME/.config/octave $HOME/.config/Skype $HOME/.config/sqlitebrowser $HOME/.config/Thunar $HOME/.config/tracker $HOME/.config/viewnior $HOME/.config/wireshark $HOME/.config/xarchiver $HOME/.config/yelp
-rm -f $HOME/.config/QtProject.conf $HOME/.config/Trolltech.conf $HOME/.config/user-dirs.dirs $HOME/.config/user-dirs.locale
-rm -fr $HOME/.quodlibet/dumps
-locate '~' | grep '~$' | xargs rm 2>/dev/null
-if [ ! -z $(which docker 2>/dev/null) ]; then
-	docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
-fi
-if [ $# -eq 1 ] && [ $1 == "-b" ]; then
-	if [ ! -z $(which bleachbit 2>/dev/null) ]; then
-		bleachbit -c adobe_reader.cache adobe_reader.mru adobe_reader.tmp amsn.cache amule.logs amule.tmp apt.autoclean apt.autoremove audacious.cache audacious.log audacious.mru beagle.cache beagle.index beagle.logs chromium.cache chromium.cookies chromium.dom chromium.form_history chromium.vacuum d4x.history deepscan.ds_store deepscan.thumbs_db deepscan.tmp easytag.logs elinks.history emesene.cache emesene.logs epiphany.cache epiphany.cookies epiphany.passwords epiphany.places evolution.cache exaile.cache exaile.downloaded_podcasts exaile.log filezilla.mru firefox.cache firefox.crash_reports firefox.dom firefox.forms firefox.vacuum flash.cache flash.cookies gedit.recent_documents gftp.cache gftp.logs gimp.tmp gl-117.debug_logs gnome.run gnome.search_history google_chrome.cache google_chrome.cookies google_chrome.dom google_chrome.form_history google_chrome.history google_chrome.passwords google_chrome.search_engines google_chrome.session google_chrome.vacuum google_earth.temporary_files google_toolbar.search_history gpodder.cache gpodder.vacuum gwenview.recent_documents hippo_opensim_viewer.cache hippo_opensim_viewer.logs java.cache kde.cache kde.recent_documents kde.tmp konqueror.cookies konqueror.current_session konqueror.url_history libreoffice.cache libreoffice.history liferea.cache liferea.cookies liferea.vacuum links2.history midnightcommander.history miro.cache miro.logs nautilus.history nexuiz.cache octave.history openofficeorg.cache openofficeorg.recent_documents opera.cache opera.cookies opera.current_session opera.dom opera.download_history opera.search_history opera.url_history pidgin.cache pidgin.logs realplayer.cookies realplayer.history realplayer.logs recoll.index rhythmbox.cache screenlets.logs seamonkey.cache seamonkey.chat_logs seamonkey.cookies seamonkey.download_history seamonkey.history secondlife_viewer.Cache secondlife_viewer.Logs sqlite3.history system.cache system.clipboard system.custom system.desktop_entry system.localizations system.recent_documents system.rotated_logs system.tmp system.trash thumbnails.cache thunderbird.cache thunderbird.cookies thunderbird.vacuum transmission.cache tremulous.cache vim.history vlc.mru vuze.backup_files vuze.cache vuze.logs vuze.tmp warzone2100.logs wine.tmp winetricks.temporary_files x11.debug_logs xine.cache yum.clean_all yum.vacuum
-	else
-		echo "bleachbit not found in \$PATH" >&2
+
+# delete shitloads of temporary files or files polluting the homedir
+#
+# $ cleanup
+# $ cleanup -b
+
+function main ()
+{
+    homedir_dirs=(
+        .AbiSuite
+        .abrt
+        .adobe
+        .agdb
+        .AMD
+        .android
+        .ansible
+        .ansible_async
+        .appletviewer
+        .aptitude
+        .aria2
+        .assaultcube_v1.104
+        .audacity-data
+        .cache
+        .cgobanrc
+        .cinnamon
+        .dbus
+        .ddd
+        .dreamchess
+        .dvdcss
+        .eclipse
+        .elinks
+        .emacs.d
+        .evolution
+        .fontconfig
+        .gconfd
+        .gdb_history
+        .gegl-0.0
+        .getdown
+        .gimp-2.8
+        .git-credential-cache
+        .gksu.lock
+        .gnash
+        .gnome
+        .gnome2
+        .gnome2_private
+        .gnote
+        .golly
+        .googleearth
+        .gstreamer-0.10
+        .gvfs
+        .hedgewars
+        .icedtea
+        .icons
+        .ipython
+        .isag.cfg
+        .java
+        .jupyter
+        .kde
+        .lftp
+        .links
+        .links2
+        .macromedia
+        .macports
+        .matlab
+        .matplotlib
+        .mc
+        .mcop
+        .mission-control
+        .mplayer
+        .muttator
+        .nautilus
+        .nedit
+        .nemo
+        .nv
+        .nvimlog
+        .octave_hist
+        .oracle_jre_usage
+        .osquery
+        .parallel
+        .pdfedit
+        .pip
+        .pki
+        .plotly
+        .pulse
+        .python27_compiled
+        .python_history
+        .quodlibet/dumps
+        .qt
+        .recently-used.xbel
+        .redhat
+        .scala_history
+        .sqlite_history
+        .sunstudio
+        .swt
+        .texmf-var
+        .themes
+        .thumbnails
+        .update-notifier
+        .vidalia
+        .wireshark
+    )
+    homedir_files=(
+        .aspell*
+        .cuda-gdbinit
+        .esd_auth
+        .fixmyserver-homedir-write-test
+        .gnuplot_history
+        .gtk-bookmarks
+        .history
+        .hivehistory
+        .hphpd.history
+        .hphpd.ini
+        .ICEauthority
+        .imsettings.log
+        .lesshst
+        .mysql_history
+        .ophcrackrc
+        .pulse-cookie
+        .recently-used
+        .rnd
+        .scala_history
+        .scm.sqlite
+        .scuba_history
+        .serfcli2
+        .sudo_as_admin_successful
+        .tilp
+        .viminfo
+        .vim/.netrwhist
+        .wget-hsts
+        .xfce4-session.verbose-log*
+        .xsession
+        .xsession-errors*
+        .ypp_42
+        .zcompdump
+        .AndroidStudio2.0/config/options/usage.statistics.xml
+        .AndroidStudio2.0/config/options/feature.usage.statistics.xml
+        .AndroidStudio2.0/config/options/statistics.application.usages.xml
+    )
+    config_dirs=(
+        abrt
+        "chromium/Default/Local Storage"
+        cinnamon-session
+        clipit
+        DjVuLibre
+        enchant
+        evince
+        evolution
+        gnome-disk-utility
+        gnome-initial-setup-done
+        gnome-session
+        goa-1.0
+        "google-chrome/Default/Local Storage"
+        google-googletalkplugin
+        gtk-2.0
+        guvcview2
+        htop
+        ibus
+        imsettings
+        kazam
+        libreoffice
+        libvirt
+        menus
+        octave
+        Skype
+        sqlitebrowser
+        Thunar
+        tracker
+        viewnior
+        wireshark
+        xarchiver
+        yelp
+    )
+    config_files=(
+        QtProject.conf
+        Trolltech.conf
+        user-dirs.dirs
+        user-dirs.locale
+    )
+    tmpfiles=(
+        www-vmtouch-*
+        www_vmtouch_db_cache.json
+        perf-*.map
+        par_preload_unpack.*
+        par_unpack.*
+        pymp-*
+        wmlock-*
+        scm-internal-stats*
+        fastzip-castree-uid-*
+        packman-fb-*
+        tmp*
+        testpilot.*
+        hhvm_*
+        gnash-cookies.*
+    )
+    for d in "${homedir_dirs[@]}"; do
+        rm -rf "$HOME/${d}"
+    done
+    for f in "${homedir_files[@]}"; do
+        rm -f "$HOME/${f}"
+    done
+    for d in "${config_dirs[@]}"; do
+        rm -rf "$HOME/.config/${f}"
+    done
+    for f in "${config_files[@]}"; do
+        rm -f "$HOME/.config/${f}"
+    done
+    for d in "${tmpfiles[@]}"; do
+        sudo rm -rf /tmp/${tmpfiles}
+    done
+    rm -f $(locate recently-used.xbel)
+    #locate '~' | grep '~$' | xargs -I% mv % ~/references/recovered_files
+
+    # firefox trash
+    cd $HOME/.mozilla 2>/dev/null
+    rmdir extensions 2>/dev/null
+    cd firefox 2>/dev/null
+    for profile in $(ls -d *.default 2>/dev/null)
+    do
+      cd $profile
+      rm -rf startupCache Cache bookmarkbackups thumbnails OfflineCache thumbnails
+      rm -f adblockplus/patterns-backup* adblockplus/cache.js chromeappstore.sqlite
+      cd ..
+    done
+
+    # clean up all docker shit
+    if [ ! -z $(which docker 2>/dev/null) ]; then
+      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
+    fi
+    if [ $# -eq 1 ] && [ $1 == "-b" ]; then
+      bleachbit_func
+    fi
+	root_func
+}
+
+function bleachbit_func ()
+{
+    if [ ! -z $(which bleachbit 2>/dev/null) ]; then
+        bleachbit  -c \
+            adobe_reader.cache \
+            adobe_reader.mru \
+            adobe_reader.tmp \
+            amsn.cache \
+            amule.logs \
+            amule.tmp \
+            apt.autoclean \
+            apt.autoremove \
+            audacious.cache \
+            audacious.log \
+            audacious.mru \
+            beagle.cache \
+            beagle.index \
+            beagle.logs \
+            chromium.cache \
+            chromium.cookies \
+            chromium.dom \
+            chromium.form_history \
+            chromium.vacuum \
+            d4x.history \
+            deepscan.ds_store \
+            deepscan.thumbs_db \
+            deepscan.tmp \
+            easytag.logs \
+            elinks.history \
+            emesene.cache \
+            emesene.logs \
+            epiphany.cache \
+            epiphany.cookies \
+            epiphany.passwords \
+            epiphany.places \
+            evolution.cache \
+            exaile.cache \
+            exaile.downloaded_podcasts \
+            exaile.log \
+            filezilla.mru \
+            firefox.cache \
+            firefox.crash_reports \
+            firefox.dom \
+            firefox.forms \
+            firefox.vacuum \
+            flash.cache \
+            flash.cookies \
+            gedit.recent_documents \
+            gftp.cache \
+            gftp.logs \
+            gimp.tmp \
+            gl-117.debug_logs \
+            gnome.run \
+            gnome.search_history \
+            google_chrome.cache \
+            google_chrome.cookies \
+            google_chrome.dom \
+            google_chrome.form_history \
+            google_chrome.history \
+            google_chrome.passwords \
+            google_chrome.search_engines \
+            google_chrome.session \
+            google_chrome.vacuum \
+            google_earth.temporary_files \
+            google_toolbar.search_history \
+            gpodder.cache \
+            gpodder.vacuum \
+            gwenview.recent_documents \
+            hippo_opensim_viewer.cache \
+            hippo_opensim_viewer.logs \
+            java.cache \
+            kde.cache \
+            kde.recent_documents \
+            kde.tmp \
+            konqueror.cookies \
+            konqueror.current_session \
+            konqueror.url_history \
+            libreoffice.cache \
+            libreoffice.history \
+            liferea.cache \
+            liferea.cookies \
+            liferea.vacuum \
+            links2.history \
+            midnightcommander.history \
+            miro.cache \
+            miro.logs \
+            nautilus.history \
+            nexuiz.cache \
+            octave.history \
+            openofficeorg.cache \
+            openofficeorg.recent_documents \
+            opera.cache \
+            opera.cookies \
+            opera.current_session \
+            opera.dom \
+            opera.download_history \
+            opera.search_history \
+            opera.url_history \
+            pidgin.cache \
+            pidgin.logs \
+            realplayer.cookies \
+            realplayer.history \
+            realplayer.logs \
+            recoll.index \
+            rhythmbox.cache \
+            screenlets.logs \
+            seamonkey.cache \
+            seamonkey.chat_logs \
+            seamonkey.cookies \
+            seamonkey.download_history \
+            seamonkey.history \
+            secondlife_viewer.Cache \
+            secondlife_viewer.Logs \
+            sqlite3.history \
+            system.custom \
+            system.desktop_entry \
+            system.localizations \
+            system.recent_documents \
+            system.rotated_logs \
+            system.trash \
+            thumbnails.cache \
+            thunderbird.cache \
+            thunderbird.cookies \
+            thunderbird.vacuum \
+            tremulous.cache \
+            vim.history \
+            vlc.mru \
+            vuze.backup_files \
+            vuze.cache \
+            vuze.logs \
+            vuze.tmp \
+            warzone2100.logs \
+            wine.tmp \
+            winetricks.temporary_files \
+            x11.debug_logs \
+            xine.cache \
+            yum.clean_all \
+            yum.vacuum
+      else
+        echo "bleachbit not found in \$PATH" >&2
+      fi
+}
+
+function root_func ()
+{
+	if [ $EUID == 0 ]; then
+		echo LoL
+#		rm -r "/usr/share/locale/{[a-dg-z]*,e!(n),fr[a-z_@]*}"
+#		rm -r /usr/share/man/[a-no-z]*
 	fi
+}
+
+if [ "${BASH_SOURCE[0]}" == "$0" ]; then
+    main "$@"
 fi
-exit 0
