shellcheck fixes + reformat with shfmt -i 4 -bn -ci -s -sr -fn -w

diff --git a/cleanup b/cleanup
--- a/cleanup
+++ b/cleanup
@@ -8,7 +8,7 @@
 set -e -u
 set -o pipefail
 
-function main ()
+function main()
 {
     homedir_dirs=(
         .AbiSuite
@@ -25,6 +25,7 @@ function main ()
         .assaultcube_v1.104
         .audacity-data
         .cache
+        .cargo
         .CFUserTextEncoding
         .cgobanrc
         .config/abrt
@@ -270,45 +271,44 @@ function main ()
     done
     for d in "${tmpfiles[@]}"; do
         # shellcheck disable=SC2086
-        rm -rf /tmp/${d} 2>/dev/null
+        rm -rf /tmp/${d} 2> /dev/null
     done
-    LOCATE=$( [[ $(uname) == Darwin ]] && echo slocate||echo locate)
+    LOCATE=$([[ $(uname) == Darwin ]] && echo slocate || echo locate)
     # shellcheck disable=SC2046
-    ${LOCATE} recently-used.xbel |xargs rm -f
+    ${LOCATE} recently-used.xbel | xargs rm -f
 
     if [ -d ~/.mozilla ]; then
         firefox_cleanup
     fi
 
     # clean up all docker shit
-    if [ -n "$(which docker 2>/dev/null)" ]; then
-      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc 2>/dev/null || true
+    if [ -n "$(which docker 2> /dev/null)" ]; then
+        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc 2> /dev/null || true
     fi
     if [ $# -eq 1 ] && [ "${1}" == "-b" ]; then
-      bleachbit_func
+        bleachbit_func
     fi
     root_func
 }
 
 # firefox trash
-function firefox_cleanup ()
+function firefox_cleanup()
 {
-    cd ~/.mozilla 2>/dev/null
-    rmdir extensions 2>/dev/null
-    cd firefox 2>/dev/null
-    for profile in $(ls -d *.default 2>/dev/null)
-    do
-      cd "${profile}"
-      rm -rf startupCache Cache bookmarkbackups thumbnails OfflineCache thumbnails
-      rm -f adblockplus/patterns-backup* adblockplus/cache.js chromeappstore.sqlite
-      cd ..
+    cd ~/.mozilla 2> /dev/null
+    rmdir extensions 2> /dev/null
+    cd firefox 2> /dev/null
+    for profile in *.default; do
+        cd "${profile}"
+        rm -rf startupCache Cache bookmarkbackups thumbnails OfflineCache thumbnails
+        rm -f adblockplus/patterns-backup* adblockplus/cache.js chromeappstore.sqlite
+        cd ..
     done
 }
 
-function bleachbit_func ()
+function bleachbit_func()
 {
-    if [ -n "$(which bleachbit 2>/dev/null)" ]; then
-        bleachbit  -c \
+    if [ -n "$(which bleachbit 2> /dev/null)" ]; then
+        bleachbit -c \
             adobe_reader.cache \
             adobe_reader.mru \
             adobe_reader.tmp \
@@ -443,17 +443,18 @@ function bleachbit_func ()
             xine.cache \
             yum.clean_all \
             yum.vacuum
-      else
-        echo "bleachbit not found in \$PATH" >&2
-      fi
+    else
+        # shellcheck disable=SC2016
+        echo 'bleachbit not found in $PATH' >&2
+    fi
 }
 
-function root_func ()
+function root_func()
 {
     if [ $EUID == 0 ]; then
         echo LoL
-#        rm -r "/usr/share/locale/{[a-dg-z]*,e!(n),fr[a-z_@]*}"
-#        rm -r /usr/share/man/[a-no-z]*
+        #        rm -r "/usr/share/locale/{[a-dg-z]*,e!(n),fr[a-z_@]*}"
+        #        rm -r /usr/share/man/[a-no-z]*
     fi
 }
 
diff --git a/old/apt-trim-depends b/old/apt-trim-depends
--- a/old/apt-trim-depends
+++ b/old/apt-trim-depends
@@ -9,72 +9,72 @@
 
 # Usage: apt-trim-depend PKGNAME ...
 
-function trim_depend ()
+function trim_depend()
 {
-	pkglist="$1"; shift
-	while [ $# -ge 1 ]; do
-		pkglist="${pkglist} $1"; shift
-	done
-	cd /tmp || return
+    pkglist="$1"
+    shift
+    while [ $# -ge 1 ]; do
+        pkglist="${pkglist} $1"
+        shift
+    done
+    cd /tmp || return
 
-	for pkg in ${pkglist}; do
-		out="$(aptitude why "${pkg}")"
-		echo "${out}" >&2
-		if [ -z "${out}" ]; then
-			echo 1
-			break
-		fi
-		read -rp "Continue? [Y/n] "
-		ret="$(tr '[:upper:]' '[:lower:]' <<< "${REPLY}"|cut -b1)"
-		if [ "${ret}" == 'y' ]; then
-			deppkg="$(tail -1 <<< "${out}"|cut -b5-|awk '{print $1}')"
-			echo "${deppkg}"
-			if apt download "${deppkg}"; then
-				echo 1
-				break
-			fi
-			pkg_filename="$(ls "${deppkg}"*.deb)"
-			dpkg-deb -R "${pkg_filename}" "${deppkg}"
-			for pkg2 in ${pkglist}; do
-				sed -ri "s/(Depends:.*)${pkg2},?/\1/g" "${deppkg}/DEBIAN/control"
-			done
-			sed -i 's/Depends:\s*,/Depends: /;s/,\s*$//' "${deppkg}/DEBIAN/control"
-			echo -n "New depends line: " >&2
-			grep '^Depends' "${deppkg}/DEBIAN/control" >&2
-			rm "${pkg_filename}"
-			dpkg-deb -b "${deppkg}"
-			mv "${deppkg}.deb" "${pkg_filename}"
-			sudo dpkg -i "${pkg_filename}"
-			rm -rf "${deppkg}" "${pkg_filename}"
-			echo 0
-		else
-			echo "Aborting..."
-			echo 1
-			break
-		fi
-	done
+    for pkg in ${pkglist}; do
+        out="$(aptitude why "${pkg}")"
+        echo "${out}" >&2
+        if [ -z "${out}" ]; then
+            echo 1
+            break
+        fi
+        read -rp "Continue? [Y/n] "
+        ret="$(tr '[:upper:]' '[:lower:]' <<< "${REPLY}" | cut -b1)"
+        if [ "${ret}" == 'y' ]; then
+            deppkg="$(tail -1 <<< "${out}" | cut -b5- | awk '{print $1}')"
+            echo "${deppkg}"
+            if apt download "${deppkg}"; then
+                echo 1
+                break
+            fi
+            pkg_filename="$(ls "${deppkg}"*.deb)"
+            dpkg-deb -R "${pkg_filename}" "${deppkg}"
+            for pkg2 in ${pkglist}; do
+                sed -ri "s/(Depends:.*)${pkg2},?/\1/g" "${deppkg}/DEBIAN/control"
+            done
+            sed -i 's/Depends:\s*,/Depends: /;s/,\s*$//' "${deppkg}/DEBIAN/control"
+            echo -n "New depends line: " >&2
+            grep '^Depends' "${deppkg}/DEBIAN/control" >&2
+            rm "${pkg_filename}"
+            dpkg-deb -b "${deppkg}"
+            mv "${deppkg}.deb" "${pkg_filename}"
+            sudo dpkg -i "${pkg_filename}"
+            rm -rf "${deppkg}" "${pkg_filename}"
+            echo 0
+        else
+            echo "Aborting..."
+            echo 1
+            break
+        fi
+    done
 }
 
-
-function main ()
+function main()
 {
-	if [ $# == '0' ]; then
-		echo "Usage: $(basename "$0") packagename ..."
-		exit 1
-	fi
-	aptwhy=$(command -v aptitude)
-	if [ -z "${aptwhy}" ]; then
-		sudo apt install aptitude
-	fi
-	unset aptwhy
-	
-	trim_depend "$@"
-	exit
-	while [ "$(trim_depend "$@")" == 0 ]; do
-		echo "Looking for more dependencies"
-	done
-}
+    if [ $# == '0' ]; then
+        echo "Usage: ${0##*/} packagename ..."
+        exit 1
+    fi
+    aptwhy=$(command -v aptitude)
+    if [ -z "${aptwhy}" ]; then
+        sudo apt install aptitude
+    fi
+    unset aptwhy
 
+    trim_depend "$@"
+    exit
+    while [ "$(trim_depend "$@")" == 0 ]; do
+        echo "Looking for more dependencies"
+    done
+}
 
 if [ "${BASH_SOURCE[0]}" == "$0" ]; then
     main "$@"
