add network target aliases

diff --git a/send b/send
--- a/send
+++ b/send
@@ -15,6 +15,35 @@ function print_ip_addr ()
     esac
 }
 
+
+function resolve_target ()
+{
+    local target="${1}"; shift
+    source "${NETWORK_TARGETS}"
+    if [ -v "${target}" ]; then
+        echo "${!target}"
+    else
+        echo "${target}"
+    fi
+}
+
+function ensure_targets_file ()
+{
+    test -d "${TARGET_ALIAS_DIR}" || mkdir -p "${TARGET_ALIAS_DIR}" && \
+        test -f "${NETWORK_TARGETS}" || \
+        touch "${NETWORK_TARGETS}" || \
+        (printf "ERROR SETTING UP NETWORK TARGETS MODULE\n" >&2 && return)
+}
+
+function add_network_target ()
+{
+    readonly local alias="${1}"; shift
+    readonly local target="${1}"; shift
+
+    ensure_targets_file
+    printf "%s=\"%s\"\n" "${alias}" "${target}" >> "${NETWORK_TARGETS}"
+}
+
 function binary ()
 {
     if command -v ncat >/dev/null 2>&1; then
@@ -30,6 +59,8 @@ function main ()
     local file
     local ip_addr
     local progname
+    readonly local TARGET_ALIAS_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/bash"
+    readonly local NETWORK_TARGETS="${TARGET_ALIAS_DIR}/network_targets"
 
     progname=$(basename "$0")
     case $progname in
@@ -50,9 +81,9 @@ function main ()
                 printf 'Usage: %s IP_Address filename1 [filename2 ...]\n' "${progname}"  >&2
                 exit 0
             fi
-            ip_addr="$1"; shift
+            ip_addr="$(resolve_target "$1")"; shift
             while [ $# != 0 ]; do
-                file="$1"; shift
+                file="$(resolve_target "${1}")"; shift
                 printf 'Receiving file %s...\n' "${file}"
                 if [ -e "${file}" ]; then
                     printf 'ERROR: file %s already exists\n' "${file}" >&2
@@ -78,6 +109,9 @@ function main ()
                 fi
                 $(binary) -v "${ip_addr}" "${portnum}" > "${file}"
             done
+            ;;
+        "send_add_target")
+            add_network_target "${@}"
             ;;
         *)
             printf 'Script called with incorrect name\n'
