WIP on stream2mp4; small fix for ramdisk but main issue is still present

diff --git a/stream2mp4 b/stream2mp4
--- a/stream2mp4
+++ b/stream2mp4
@@ -9,6 +9,8 @@ set -o pipefail
 # $ stream2mp4 URL
 # Once the script is done running, the mp4 file will be in your ~/Downloads folder
 
+readonly FRAGMENT_DIRNAME="fragments"
+
 function usage ()
 {
     cat << EOF
@@ -22,7 +24,7 @@ function download_m3u_file ()
 {
     local readonly url="${1}"; shift
 
-    m3u_file="$(basename "${url}")"
+    m3u_file="playlist.m3u"     # hardcode value to avoid too long file names
     curl -s "${url}" -o "${m3u_file}"
     printf "%s\n" "${m3u_file}"
 }
@@ -32,26 +34,29 @@ function download_fragments ()
     local readonly url="${1}"; shift
     local readonly m3u_file="${1}"; shift
     local readonly baseurl="$(dirname "${url}")"
-    local readonly fragment_dirname="fragments"
 
-    mkdir -p "${fragment_dirname}"
+    mkdir -p "${FRAGMENT_DIRNAME}"
 
-    cd "${fragment_dirname}"
-    grep -v '^#EXT' "../${m3u_file}" | while read; do
-        printf "Downloading fragment %s\n" "${REPLY}" >&2
-        curl -s --retry 20 --retry-delay 1 --retry-connrefused "${baseurl}/${REPLY}" -o "$(basename "${REPLY}")"
-    done
+    cd "${FRAGMENT_DIRNAME}"
+    aria2c -x10 -s5 -m0 -j20 -i="../${m3u_file}"
+    #grep -v '^#EXT' "../${m3u_file}" | while read; do
+    #    printf "Downloading fragment %s\n" "${REPLY}" >&2
+        #curl -s --retry 20 --retry-delay 1 --retry-connrefused "${baseurl}/${REPLY}" -o "$(basename "${REPLY}")"
+    #done
     cd - > /dev/null
 
-    printf "%s/%s\n" "$(pwd)" "${fragment_dirname}"
+    printf "%s/%s\n" "$(pwd)" "${FRAGMENT_DIRNAME}"
 }
 
 function prep_m3u_file ()
 {
     local readonly m3u_file="${1}"; shift
     local readonly fragment_dir="${1}"; shift
+    #local readonly url="${1}"; shift
+    #local readonly baseurl="$(dirname "${url}")"
 
-    sed -i -E "/^#EXT/d;s/$/'/;s#^[^/]*#file '${fragment_dir}#" "${m3u_file}"
+    #sed -i -E "/^#EXT/d;s/$/'/;s#^[^/]*#file '${fragment_dir}#" "${m3u_file}"
+    sed -i -E "/^#EXT/d;s#^[^/]*#file '${fragment_dir}#" "${m3u_file}"
 }
 
 function convert_to_mp4 ()
@@ -63,8 +68,8 @@ function convert_to_mp4 ()
 
 function delete_tempfiles ()
 {
-    local readonly fragment_dir="${1}"; shift
-    rm -r "${fragment_dir}"
+    local readonly tmpdir="${1}"; shift
+    rm -r "${tmpdir}/${FRAGMENT_DIRNAME}"
 }
 
 function main ()
@@ -117,7 +122,7 @@ function main ()
     local readonly fragment_dir="$(download_fragments "${url}" "${m3u_file}")"
     prep_m3u_file "${m3u_file}" "${fragment_dir}"
     convert_to_mp4 "${m3u_file}" "${output_file}"
-    delete_tempfiles "${fragment_dir}"
+    delete_tempfiles "${tmpdir}"
 }
 
 if [ "${BASH_SOURCE[0]}" == "$0" ]; then
